// This file is generated by scripts/generate-paths.ts
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-static-paths" {
  interface Paths {
  "/": Record<never, never>,
  "/create-organization": Record<never, never>,
  "/deals": Record<never, never>,
  "/deals/[dealId]": {"dealId": string},
  "/sign-in/[...sign-in]": {"sign-in": string[]},
  "/sign-up/[...sign-up]": {"sign-up": string[]}
  }
}
